pagopa/eng-github-actions-iac-template

- azure/github-self-hosted-runner-azure-cleanup-action/action.yml
> feat: Added github-self-hosted-runner-azure-cleanup-action

- azure/github-self-hosted-runner-azure-cleanup-action/action.yml
- azure/github-self-hosted-runner-azure-create-action/action.yml
Added check to github-self-hosted-runner-azure* actions, to kill run in case the PAT token is incorrect.
> feat: Added checks for github-selfhosted-runner-azure in case the PAT token is invalid

- azure/github-self-hosted-runner-azure-create-action/action.yml
- upgrated the last version image of runner
- minor fix
- removed echos in bash not needed
Allow to use the last version of docker runner and avoid wrong echos
> feat: Upgrade templates and fix bash script

- aws/terraform-plan-aws-action/action.yml
> fix: Correct input name in aws plan action

- azure/github-self-hosted-runner-azure-create-action/action.yml
> fix: Upgrated github runner to 1.4.2

- azure/github-self-hosted-runner-azure-create-action/action.yml
- upgrated template azure/github-self-hosted-runner-azure-create-action/action.yml to use the last version of github runner
Avoid deprecation problems with self hosted runner for github
> feat: Upgrated github runner to 1.5.0

- azure/github-self-hosted-runner-azure-create-action/action.yml
> fix: Upgrade default image

- azure/github-self-hosted-runner-azure-create-action/action.yml
> fix: Upgrade default image to 1.6.2

- aws/create-github-runner-aws-action/README.md
- aws/remove-github-runner-aws-action/README.md
Update the docs that contained an imprecise information.
- Rectify the README of `create-github-runner-aws-action`
- Rectify the README of `remove-github-runner-aws-action`
Docs were not precise.
> docs: Correct action reference in readme

- azure/terraform-static-analysis/README.md
- azure/terraform-static-analysis/action.yml
Added a new action to perform static analysis on an Azure Terraform project
To avoid code duplication.
Tested on a branch of the repository "pagopa-infra".
> feat: Static azure analysis action

- azure/github-self-hosted-runner-azure-create-action/action.yml
> feat: Use latest tag in the default self_hosted_runner_image_tag

- azure/github-self-hosted-runner-azure-create-action/action.yml
Pin the default docker image tag
This action is becoming useless and no more compatible with the new approach.
Pinning the latest compatible version allows us to migrate to container app jobs without affecting existing workload.
Can be merge after [#18](https://github.com/pagopa/github-self-hosted-runner-azure/pull/18)
> chore: Pin Docker image tag

- azure/github-self-hosted-runner-azure-create-action/action.yml
> feat: Added v3.1.0 github action with yarn

- aws/create-github-runner-aws-action/action.yml
- aws/remove-github-runner-aws-action/action.yml
Some actions used where pinned to the major version instead of the commit.
- Pin action [configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) used in [create-github-runner-aws-action](https://github.com/pagopa/eng-github-actions-iac-template/tree/main/aws/create-github-runner-aws-action) and [remove-github-runner-aws-action](https://github.com/pagopa/eng-github-actions-iac-template/tree/main/aws/remove-github-runner-aws-action) to the commit of the tag v4.0.1
Improved security and adherence to company policy.
Launched a [example workflow](https://github.com/pagopa/terraform-aws-githubrunner/actions/runs/7278467999) using both actions with this branch ref.
> fix: Pin used actions to the commit

- .gitignore
- azure/terraform-sh-apply-azure-action/README.md
- azure/terraform-sh-apply-azure-action/action.yml
- added action and readme
Allow to launch terraform.sh with apply
> feat: Added azure/terraform-sh-apply-azure-action 

- global/release-action/.releaserc.json
- global/release-action/README.md
- global/release-action/action.yml
- added release action
- added readme
- added config file for release action
Allow to use a release action pipeline, with all the features needed and updated with the last actions versions
> feat: Create release action

- .github/workflows/pr-title.yml
Use the last version to avoid warnings
> feat: upgrated PR title action

- azure/terraform-static-analysis/README.md
- azure/terraform-static-analysis/action.yml
> feat: Terraform-static-analysis updated to v1.89.1

- global/release-action/README.md
- global/release-action/action.yml
- added output for release action
- better readme
Allow to use the release outputs
> feat: Release action added outputs

- global/release-with-docker/README.md
- global/release-with-docker/action.yml
Allow to create a release and generate a docker image with the same version
> feat: Added release with docker action

- global/docker-build-push/README.md
- global/docker-build-push/action.yml
- global/release-with-docker/action.yml
- added docker build push
- fix release action with context input
Allow to build and push with docker, and upload the image into the ghcr
> feat: Added docker build push

- global/get-modifed-folders/README.md
- global/get-modifed-folders/action.yml
> feat: PAYMCLOUD-101-Add-new-github-action-template-to-sparse-checkout-modified-folders

- global/get-modifed-folders/README.md
- global/get-modifed-folders/action.yml
> feat: [PAYMCLOUD-101] Rename input parameters for clarity

- global/release-action/action.yml
- updated semantic-release version to 24.0.1
- updated semantic-github to 11.0.0
- added tag_format input
Allow to use tag_format input, and upgrade extensions to avoid problems with search api
> feat: release-action upgrated extensions

- global/get-modifed-folders/action.yml
- Updated detection logic to use file size checks instead of pattern matching for enhanced reliability.
- Added `FileNotFoundError` exception handling to gracefully manage missing paths.
- Improved the clarity of output messages during execution.
This refactor improves the stability and reliability of the folder change detection mechanism by addressing cases where files may be missing and ensuring better user feedback.
Manual testing was conducted with scenarios involving missing files, folder size changes, and error handling to validate the robustness of the updated logic.
> feat: Refactor folder change detection with improved error handling

- global/get-modifed-folders/action.yml
> feat: Add inspection for local source dependencies in paths

- global/get-modifed-folders/action.yml
Now this action skip the binary files, and manage
the subfolders in a correct way.
> fix: Action global/get-modified-folders now skip binaries files

- global/get-modifed-folders/action.yml
- Removed unnecessary debug print statements for cleaner console output.
- Refined file scanning and recursive traversal for improved accuracy.
- Enhanced dependency inspection with more informative and detailed debug logs.
- Fixed directory handling issues, ensuring valid directories are processed correctly.
- Adjusted dependency filtering and deduplication logic for better reliability.
These changes aim to enhance the functionality and reliability of the folder dependency scanning logic. By refining path handling, cleaning redundant code, improving debug logging, and fixing directory handling, the overall accuracy and maintainability of the system are significantly improved.
Changes have been tested by:
- Verifying correct directory and path handling for multiple scenarios.
- Examining …
> fix: Fix dependency scanning

- azure/terraform-static-analysis/action.yml
> feat: added log for static analysis folder
